'use client'
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Provider } from "react-redux";
import { Store } from "./Redux/Store";
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";

import "./globals.css"
import { ThemeProvider } from "@/components/ui/themeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
/*
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
*/
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
 <ThemeProvider
    attribute="class"
    defaultTheme="system"
    enableSystem
    disableTransitionOnChange
  >
    <html lang="en" className="" >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <Provider store={Store} >
<div className="h-[10vh]"> 
  <Navbar  />
</div>
        {children}
          <Footer />
        </Provider>
      </body>
    </html>
  </ThemeProvider>

  );
}
